export enum Selectors {
  SHUTTER_LOGIN_FIELD = '#login-username',
  SHUTTER_PASS_FIELD = '#login-password',
  SHUTTER_LOGIN_BUTTON = '#login',
  SHUTTER_FOOTER = '#site-footer',
  SHUTTER_DOWNLOAD_BUTTON = '.prod-download-btn',
  STORYBLOCKS_LOGIN_FIELD = '#email',
  STORYBLOCKS_PASS_FIELD = '#password',
  STORYBLOCKS_LOGIN_BUTTON = 'button[type=submit]',
  STORYBLOCKS_HOME = '#storyblocks-home',
  VIDEOBLOCKS_LOGIN_FIELD = '#email',
  VIDEOBLOCKS_PASS_FIELD = '#password',
  VIDEOBLOCKS_LOGIN_BUTTON = 'button[type=submit]',
  VIDEOBLOCKS_HOME = '.redesignedVideoHomeWrapper',
  AUDIOBLOCKS_LOGIN_FIELD = '#email',
  AUDIOBLOCKS_PASS_FIELD = '#password',
  AUDIOBLOCKS_LOGIN_BUTTON = 'button[type=submit]',
  AUDIOBLOCKS_HOME = '.wrapper',
}
