export enum Selectors {
  SHUTTER_LOGIN_FIELD = '#login-username',
  SHUTTER_PASS_FIELD = '#login-password',
  SHUTTER_LOGIN_BUTTON = '#login',
  SHUTTER_FOOTER = '#site-footer',
  SHUTTER_CONTENT_PAGE = '#content,.body-content',
  SHUTTER_FILE_ID = '.product-id',
  SHUTTER_DOWNLOAD_BUTTON = '.prod-download-btn',
  SHUTTER_DOWNLOAD_CONFIRM_BUTTON = '.js_download-btn',
  SHUTTER_MANUAL_DOWNLOAD_BUTTON = '[data-track="click.downloadNotStart.manual"]',
  STORYBLOCKS_LOGIN_FIELD = '#email',
  STORYBLOCKS_PASS_FIELD = '#password',
  STORYBLOCKS_LOGIN_BUTTON = 'button[type=submit]',
  STORYBLOCKS_HOME = '#imageHomepage',
}
